config/routes.rb
Rails.application.routes.draw do
  resources :locations

  root 'home#index'
  get 'maps'=>"maps#index",:as=>"maps_index"
  get '/location/save/:lat/:lng/:latpos/:lngpos/:desc'=>"locations#new",:as=>"save_location", :requirements => { :lat => /.*/ ,:long=>/.*/}
  devise_for :users

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to "/maps"
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if user_signed_in?
    @locations = current_user.location
      respond_with(@locations)
    else
      redirect_to new_user_session_path
    end
  end

  def show
    respond_with(@location)
  end

  def new
    @location = Location.new
    lat=params[:lat].insert(params[:latpos].to_i,".")
    lng=params[:lng].insert(params[:lngpos].to_i,".")

    @location.latlong=lat+","+lng

    @location.pos_name=params[:desc]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
  end

  def create
  if user_signed_in?
    @location = Location.new(location_params)
    @location.user_id=current_user.id
    @location.email=current_user.email
    if @location.save
      redirect_to root_path
    else
    respond_with(@location)
    end
  else
    redirect_to new_user_session_path
  end
  end

  def update
    @location.update(location_params)
    respond_with(@location)
  end

  def destroy
    @location.destroy
    respond_with(@location)
  end
  def save_loc
    @location=Location.new(location_params)
    if (@location.save)
      redirect_to root_path
    else
      respond_with(@location)
    end
  end
  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:user_id, :latlong, :pos_name, :email)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= content_for?(:title) ? yield(:title) : "Abacus" %></title>
<%= csrf_meta_tags %>

<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <![endif]-->

<%= stylesheet_link_tag "application", :media => "all" %>

<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

<%= javascript_include_tag "application" %>
</head>
<body>
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand whity" href="/">Abacus</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">

        <li><a href="/">Home</a></li>

        <li><%= link_to "My Locations", '/locations'  %></li>
<%if user_signed_in?%>

  <li>        <%= link_to('Logout'+current_user.name.to_s, destroy_user_session_path, :method => :delete,:class=>"link") %></li>
      <%else%>
        <li>        <%=link_to('Login',new_user_session_path)%></li>
      <%end%>
      </ul>
    </div>
  </div>
</div>
<div class="container">

  <div id="ajaxarea"></div>
  <div class="row">
    <div class="col-lg-9">
      <%= bootstrap_flash %>
            <%= yield %>
    </div>
  </div><!--/row-->


</div> <!-- /container -->
<%if user_signed_in?%>

  <div id="map-canvas"></div>

<%end%>
<footer>
  <p>Done for Webaholics at <a href="http://www.abacus.org.in" target="_blank">abacus15</a> by <br><%=gravatar_image_tag("sureshprasanna70@gmail.com",:class=>"img-circle",size:15)%> <%=link_to('Suresh Prasanna','http://about.me/sureshprasannavg',:target=>"_blank")%> and <%=link_to("Dharmesh","http://dharmeshceg.wordpress.com",:target=>"_blank")%>  <%=gravatar_image_tag("rrdharmesh@gmail.com",:class=>"img-circle",size:15)%></p>
</footer>

<script src="https://maps.googleapis.com/maps/api/js?v=363882.exp&signed_in=false"></script>
<script>

 if(window.location.href.substr(-2) !== "?r") {
      window.location = window.location.href + "?r";
    }
    var infowindow = new google.maps.InfoWindow();
function initialize() {
  geocoder = new google.maps.Geocoder();

  var mapOptions = {
zoom: 12,
      center: new google.maps.LatLng(13.082488002506816,80.27572631835938)
  };
  map = new google.maps.Map(document.getElementById('map-canvas'),
      mapOptions);

  google.maps.event.addListener(map, 'click', function(e) {
      placeMarker(e.latLng, map);
      });
}
function placeMarker(position, map) {
  var input = position;
  var lat = parseFloat(input["k"]);
  var lng = parseFloat(input["D"]);
  var latlng = new google.maps.LatLng(lat, lng);
  geocoder.geocode({'latLng': latlng}, function(results, status) {
      console.log(results);
      if (status == google.maps.GeocoderStatus.OK) {
      if (results[1]) {
      map.setZoom(11);
      marker = new google.maps.Marker({
position: latlng,
map: map
});
      google.maps.event.addListener(marker, 'click', function() {
        console.log(lat) 
        latString=lat.toString()
        lngString=lng.toString()

        latdotpos=latString.indexOf(".");
        lngdotpos=lngString.indexOf(".");
        lat=latString.split('.').join("");
        lng=lngString.split('.').join("");
        var url="location/save/"+lat+"/"+lng+"/"+latdotpos+"/"+lngdotpos+"/"+results[1].formatted_address
        console.log(url)
        var infocontent = "<p><b>"+results[1].formatted_address+"<br><a href="+url+" data-remote='true'>Click to save location</a>";
        infowindow.setContent(infocontent);
        infowindow.open(map, marker);
        });
      }
      else {
      alert('Geocoder failed due to: ' + status);
      }
      }
});
}
function placeMarker1(lat,lng) {
  var lat = lat;
  var lng = lng;
  var latlng = new google.maps.LatLng(lat, lng);
  geocoder.geocode({'latLng': latlng}, function(results, status) {
      console.log(results);
      if (status == google.maps.GeocoderStatus.OK) {
      if (results[1]) {
      map.setZoom(11);
      marker = new google.maps.Marker({
position: latlng,
map: map
});
      map.panTo(latlng);
      google.maps.event.addListener(marker, 'click', function() {
        console.log(lat) 
        latString=lat.toString()
        lngString=lng.toString()

        latdotpos=latString.indexOf(".");
        lngdotpos=lngString.indexOf(".");
        lat=latString.split('.').join("");
        lng=lngString.split('.').join("");
        var url="location/save/"+lat+"/"+lng+"/"+latdotpos+"/"+lngdotpos+"/"+results[1].formatted_address
        console.log(url)
        var infocontent = "<p><b>"+results[1].formatted_address+"<br>";
        infowindow.setContent(infocontent);
        infowindow.open(map, marker);
        });


      }
      else {
      alert('Geocoder failed due to: ' + status);
      }
      }
});
}

google.maps.event.addDomListener(window, 'load', initialize);
console.log("here")

</script>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <label class="whity">Location</label><br>
    <%= f.text_field :latlong,:class=>"form-control"%><br>
  </div>
  <br>
  <div>
    <label class="whity">Location name</label>
    <%= f.text_field :pos_name,:class=>"form-control" %>
  </div>
  <br>
  <div class="actions">
    <input type="submit" value="Save location" class="btn btn-success">
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1 class="whity">Saved locations</h1>

<table class="table table-responsive table-bordered">
  <thead>
    <tr>
      <th class="whity">Lat Long</th>
      <th class="whity">Pos name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td class="whity"><%= location.latlong %></td>
        <td class="whity"><%= location.pos_name %></td>
        <%latlng=location.latlong.split(',')%>
        <td><button onclick="placeMarker1(<%=latlng[0]%>,<%=latlng[1]%>)" class="btn btn-success"><i class="fa fa-map-marker"></i> Show on map</button> </td>
        <td><%= link_to edit_location_path(location), :class=>"btn btn-info" do %>
          <i class="fa fa-edit"></i>  Edit </td>
      <%end%>
      <td><%= link_to location, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" do%>
      <i class="fa fa-trash-o"></i> Delete
    <%end%>
    </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/new.js.erb
$('#ajaxarea').html("<%= escape_javascript(render(:partial =>"form"))%>")

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Latlong:</strong>
  <%= @location.latlong %>
</p>

<p>
  <strong>Pos name:</strong>
  <%= @location.pos_name %>
</p>


<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>